### ISSUE TITLE
Android Compile Error

### ISSUE THREAD

**Issue by GregSlazinski** [NVIDIAGameWorks/PhysX-3.4#45]
https://github.com/NVIDIAGameWorks/PhysX-3.4/blob/c7a921796332e8fcd51f3e05c1a318a41282e1e2/PhysX_3.4/Source/LowLevelCloth/src/neon/NeonSolverKernel.cpp#L43

Hi,

I'm getting an compilation error for Android:
```
PhysX/Source/LowLevelCloth/src/neon/NeonSolverKernel.cpp:43:55: error: unknown type name 'PxProfileZone'; did you mean 'profile::PxProfileZone'?
                      IterationStateFactory& factory, PxProfileZone* profileZone)
                                                      ^~~~~~~~~~~~~
                                                      profile::PxProfileZone
../PhysX/Source/LowLevelCloth/include\Factory.h:44:7: note: 'profile::PxProfileZone' declared here
class PxProfileZone;
```
I think this should be `profile::PxProfileZone` instead of `PxProfileZone` ?

However even after the fix, the file won't compile.
I'm trying to use my own compilation toolchain without having to use cygwin.

////////////////////////////////////

Also another problem:
NeonCollision.cpp
NeonSelfCollision.cpp
NeonSolverKernel.cpp
Use `__ARM_NEON__` which fails to compile on Android Arm64
`__ARM_NEON` should be used instead.
See here:
https://github.com/magnumripper/JohnTheRipper/issues/1998

You already test for it in 
PxPreprocessor.h:
```
#if defined(_M_ARM) || defined(__ARM_NEON__) || defined(__ARM_NEON)
#define PX_NEON 1
```
so perhaps the header should be included and PX_NEON tested instead?

**Comment by AlesBorovicka** [comment]
We should support custom android builds in 4.0. The default target should be armeabi-v7a with NEON.
